<a href="https://colab.research.google.com/github/DivyaBharsakle/EDS_342_Divya-Bharsakle/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array2=np.array([[10,11,12],[13,14,15],[16,17,18]])
array2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
array1
array2
print("\nAddition of two matrices: ")
print(np.add(array1,array2))


Addition of two matrices: 
[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [ ]:
array1
array2
print("\nSubtraction of two matrices: ")
print(np.subtract(array1,array2))


Subtraction of two matrices: 
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [ ]:
array1
array2
print("\nDivision of two matrices: ")
print(np.divide(array1,array2))


Division of two matrices: 
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]


In [ ]:
array1
array2
print("\nMultiplication of two matrices: ")
print(np.multiply(array1,array2))


Multiplication of two matrices: 
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
