<a href="https://colab.research.google.com/github/DivyaBharsakle/EDS_342_Divya-Bharsakle/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy

In [ ]:
import numpy

arr = numpy.array([24,25,57,87,54])

print(arr)

[24 25 57 87 54]


In [ ]:
import numpy as np

In [ ]:
import numpy
arr = np.array([24,25,57,87,54])

print(arr)

[24 25 57 87 54]


In [ ]:
print(np.__version__)

1.22.4


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.array(45)

print(arr)


45


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[[3,4,5],[3,8,5],[6,8,2]],[[4,2,6],[6,3,8],[3,6,0]]])
print(arr)

[[[3 4 5]
  [3 8 5]
  [6 8 2]]

 [[4 2 6]
  [6 3 8]
  [3 6 0]]]


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [ ]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(d.ndim)

3


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=8)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[[[[1 2 3 4]]]]]]]]
number of dimensions : 8


In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

[5 7 9]


In [ ]:
a=np.array([4,3,6])
b=np.array([2,1,6])
c=a-b
print(c)

[2 2 0]


In [ ]:
a=np.array([4,3,6])
b=np.array([2,1,6])
c=a*b
print(c)

[ 8  3 36]


In [ ]:
a=np.array([4,3,6])
b=np.array([2,1,6])
c=a/b
print(c)

[2. 3. 1.]


In [ ]:
arr1=np.array([1,2,3])
arr2=arr1.copy()
arr2[0]=4
print(arr1)
print(arr2)

[1 2 3]
[4 2 3]


In [ ]:
arr1=np.array([4,5,9])
arr2=arr1.copy()
arr2[2]=6
print(arr1)
print(arr2)

[4 5 9]
[4 5 6]


In [ ]:
arr1=np.array([4,5,9])
arr2=arr1.view()
arr2[2]=6
print(arr1)
print(arr2)

[4 5 6]
[4 5 6]


In [ ]:
arr1=np.array([4,5,9])
arr2=np.array([5,4,3])
arr3=np.vstack((arr1,arr2))
print(arr3)

[[4 5 9]
 [5 4 3]]


In [ ]:
arr1=np.array([4,5,9])
arr2=np.array([5,4,3])
arr3=np.array([1,2,3])
arr4=np.vstack((arr1,arr2,arr3))
print(arr4)

[[4 5 9]
 [5 4 3]
 [1 2 3]]


In [ ]:
arr1=np.array([4,5,9])
arr2=np.array([5,4,3])
arr3=np.array([1,2,3])
arr4=np.column_stack((arr1,arr2,arr3))
print(arr4)

[[4 5 1]
 [5 4 2]
 [9 3 3]]


In [ ]:
arr1=np.array([4,5,9])
arr2=np.array([5,4,3])
arr3=np.array([1,2,3])
arr4=np.row_stack((arr1,arr2,arr3))
print(arr4)

[[4 5 9]
 [5 4 3]
 [1 2 3]]


In [ ]:
arr1=np.array([4,5,9])
arr2=np.array([5,4,3])
arr3=np.array([1,2,3])
arr4=np.hstack((arr1,arr2,arr3))
print(arr4)

[4 5 9 5 4 3 1 2 3]


In [ ]:
import numpy as np

# input array
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking 2 1-d arrays
c = np.stack((a, b),axis=0)
print(c)


[[1 2 3]
 [4 5 6]]


In [ ]:
# stack 2 1-d arrays column-wise
np.stack((a,b),axis=1)


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#stacking 2 arrays along -1 axis
np.stack((a,b),axis=-1)


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# input arrays
x=np.array([[1,2,3],
			[4,5,6]])

y=np.array([[7,8,9],
			[10,11,12]])


In [ ]:
np.stack((x,y),axis=0)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
np.stack((x,y),axis=1)


array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

In [ ]:
np.stack((x,y),axis=2)


array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [ ]:
x=np.array([[1,2,3],
			[4,5,6]])
y=np.array([[7,8,9],
			[10,11,12]])
z=np.array([[13,14,15],
			[16,17,18]])

np.stack((x,y,z),axis=0)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [ ]:
np.stack((x,y,z),axis=1)


array([[[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15]],

       [[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18]]])

In [ ]:
np.stack((x,y,z),axis=2)


array([[[ 1,  7, 13],
        [ 2,  8, 14],
        [ 3,  9, 15]],

       [[ 4, 10, 16],
        [ 5, 11, 17],
        [ 6, 12, 18]]])

In [ ]:
arr=np.array([3,5,8,0])
print(np.sort(arr))

[0 3 5 8]


In [ ]:
arr=np.array([[3,5,0],[1,0,9]])
print(np.sort(arr))

[[0 3 5]
 [0 1 9]]


In [ ]:
arr=np.array([3,5,8,0])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[3 8]


In [ ]:
import numpy as np
list1=[x for x in range(0,91,3)]
a=np.array(list1)
print(a)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90]


In [ ]:
list1=[x for x in range(0,91,3)]
a=np.array(list1)
print(a)
print(type(list1))
print(type(a))

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90]
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
b=np.arange(40,0,-2)
print(b)

[40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10  8  6  4  2]


In [ ]:
b=np.arange(40,0,-2).reshape(2,10)
print(b)

[[40 38 36 34 32 30 28 26 24 22]
 [20 18 16 14 12 10  8  6  4  2]]


In [ ]:
b=np.arange(50,0,-1)
print(b)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1]


In [ ]:
b=np.arange(50,0,-1).reshape(5,10)
print(b)

[[50 49 48 47 46 45 44 43 42 41]
 [40 39 38 37 36 35 34 33 32 31]
 [30 29 28 27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14 13 12 11]
 [10  9  8  7  6  5  4  3  2  1]]


In [ ]:
nparray=np.empty((4,4),int)
nparray

array([[           55079104,                   0,        489626271856,
               481036337263],
       [       450971566194,        498216206433,        137438953573,
               476741369961],
       [       498216206435,        137438953580,        476741369958,
               137438953586],
       [       433791696996,        450971566198,        433791696995,
        4696453004809732096]])

In [ ]:
z=np.linspace(0,300,5)
print(z)

[  0.  75. 150. 225. 300.]


In [ ]:
a=np.array([1,3,4,5,3])
b=np.array([1,3,4,5,3])
print(np.where(a==b))


(array([0, 1, 2, 3, 4]),)


In [ ]:
arr=np.array([1,3,4,5,3])
x=np.where(a==3)
print(x)

(array([1, 4]),)


In [ ]:
arr=np.array([10,50,70,20,10,40,60,65])
x=np.where(arr%2==0)
print(x)

(array([0, 1, 2, 3, 4, 5, 6]),)


In [ ]:
arr=np.array([1,5,9,4])
x=np.searchsorted(arr,9)
print(x)

2


In [ ]:
import numpy as np
array = np.array([1,2,3,4])
x = np.searchsorted(arr, 1, side='right')
print(x)

1


In [ ]:
arr=np.array([1,5,9,4])
x=np.searchsorted(arr,[9,1,3])
print(arr)
print(x)

[1 5 9 4]
[2 0 1]


In [ ]:
array1=np.array([1,2,3,4,5,9,6,7,8,9,9])
print(np.std(array1))
print(np.min(array1))
print(np.sum(array1))
print(np.median(array1))
print(np.mean(array1))
from scipy import stats
print("Most Frequent Element=",stats.mode(array1)[0])
print("Number of Occurances=",stats.mode(array1)[1])
print(np.var(array1))

2.7990553306073913
1
63
6.0
5.7272727272727275
Most Frequent Element= [9]
Number of Occurances= [3]
7.834710743801653


<ipython-input-72-523185d54aeb>:8: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print("Most Frequent Element=",stats.mode(array1)[0])
<ipython-input-72-523185d54aeb>:9: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print("Number of Occurances=",stats.mode(array1)