<a href="https://colab.research.google.com/github/DivyaBharsakle/EDS_342_Divya-Bharsakle/blob/main/Practical_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Read the dataset into an array
data = np.genfromtxt('/content/12th_Result.csv', delimiter=',', skip_header=1)
print("Dataset:")
print(data)
print()

transposed_data = data.T
print("Transposed Matrix:")
print(transposed_data)
print()

row_sums = np.sum(data, axis=1)
print("Row Sums:")
print(row_sums)
print()

column_avgs = np.mean(data, axis=0)
print("Column Averages:")
print(column_avgs)
print()

scaled_data = 2 * data
print("Scaled Matrix:")
print(scaled_data)
print()

elementwise_scaled_data = data * 2
print("Element-wise Scaled Matrix:")
print(elementwise_scaled_data)
print()

matrix_product = np.dot(data, data.T)
print("Matrix Product:")
print(matrix_product)
print()

determinant = np.linalg.det(data)
print("Determinant:")
print(determinant)
print()

print("Horizontal stacking:")
stacked_horizontal = np.hstack((data, data))
print(stacked_horizontal)

print("Vertical stacking:")
stacked_vertical = np.vstack((data, data))
print(stacked_vertical)

custom_sequence = np.arange(0, 10, 2)
print("Custom sequence:", custom_sequence)

print("Sum of each row:", np.sum(data, axis=1))
print("Mean of each column:", np.mean(data, axis=0))

print("Square root of each element:", np.sqrt(data))
print("Exponential of each element:", np.exp(data))

copy_data = np.copy(data)
view_data = data.view()
print("Copied array:\n", copy_data)
print("Viewed array:\n", view_data)

data_stack = np.stack((data, data))
print("Data stacking:\n", data_stack)

indices = np.where(data > 70)
print("Indices where data > 70:\n", indices)

sorted_data = np.sort(data, axis=0)
print("Sorted data:\n", sorted_data)

unique_elements, counts = np.unique(data, return_counts=True)
print("Unique elements:", unique_elements)
print("Counts:", counts)

broadcasted_data = data + 10
print("Broadcasted data:\n", broadcasted_data)


Dataset:
[[540.  70.  80.  77.  31.  44.  58.  64.  74.]
 [320.  60.  70.  64.  41.  55.  57.  45.  80.]
 [460.  55.  60.  61.  51.  66.  56.  64.  73.]
 [850.  64.  50.  67.  61.  77.  78.  80.  72.]
 [650.  78.  40.  34.  71.  33.  64.  45.  78.]
 [314.  71.  59.  80.  80.  45.  36.  26.  77.]
 [750.  80.  67.  49.  45.  56.  34.  34.  76.]
 [560.  67.  74.  65.  64.  67.  38.  75.  75.]
 [468.  50.  85.  34.  48.  78.  37.  78.  70.]]

Transposed Matrix:
[[540. 320. 460. 850. 650. 314. 750. 560. 468.]
 [ 70.  60.  55.  64.  78.  71.  80.  67.  50.]
 [ 80.  70.  60.  50.  40.  59.  67.  74.  85.]
 [ 77.  64.  61.  67.  34.  80.  49.  65.  34.]
 [ 31.  41.  51.  61.  71.  80.  45.  64.  48.]
 [ 44.  55.  66.  77.  33.  45.  56.  67.  78.]
 [ 58.  57.  56.  78.  64.  36.  34.  38.  37.]
 [ 64.  45.  64.  80.  45.  26.  34.  75.  78.]
 [ 74.  80.  73.  72.  78.  77.  76.  75.  70.]]

Row Sums:
[1038.  792.  946. 1399. 1093.  788. 1191. 1085.  948.]

Column Averages:
[545.77777778  66.11

<ipython-input-47-8c34614cd5b4>:59: RuntimeWarning: overflow encountered in exp
  print("Exponential of each element:", np.exp(data))


In [ ]:
import numpy as np

# Read the dataset into an array
data = np.genfromtxt('/content/Sem_Credits.csv', delimiter=',', skip_header=1)
print("Dataset:")
print(data)
print()

transposed_data = data.T
print("Transposed Matrix:")
print(transposed_data)
print()

row_sums = np.sum(data, axis=1)
print("Row Sums:")
print(row_sums)
print()

column_avgs = np.mean(data, axis=0)
print("Column Averages:")
print(column_avgs)
print()

scaled_data = 2 * data
print("Scaled Matrix:")
print(scaled_data)
print()

elementwise_scaled_data = data * 2
print("Element-wise Scaled Matrix:")
print(elementwise_scaled_data)
print()

matrix_product = np.dot(data, data.T)
print("Matrix Product:")
print(matrix_product)
print()

print("Horizontal stacking:")
stacked_horizontal = np.hstack((data, data))
print(stacked_horizontal)

print("Vertical stacking:")
stacked_vertical = np.vstack((data, data))
print(stacked_vertical)

custom_sequence = np.arange(0, 10, 2)
print("Custom sequence:", custom_sequence)

print("Sum of each row:", np.sum(data, axis=1))
print("Mean of each column:", np.mean(data, axis=0))

print("Square root of each element:", np.sqrt(data))
print("Exponential of each element:", np.exp(data))

copy_data = np.copy(data)
view_data = data.view()
print("Copied array:\n", copy_data)
print("Viewed array:\n", view_data)

data_stack = np.stack((data, data))
print("Data stacking:\n", data_stack)

indices = np.where(data > 70)
print("Indices where data > 70:\n", indices)

sorted_data = np.sort(data, axis=0)
print("Sorted data:\n", sorted_data)

unique_elements, counts = np.unique(data, return_counts=True)
print("Unique elements:", unique_elements)
print("Counts:", counts)

broadcasted_data = data + 10
print("Broadcasted data:\n", broadcasted_data)


Dataset:
[[23.   6.   6.   8.4  5.   7.6  7. ]
 [45.   7.   8.   6.5  6.4  8.6  8. ]
 [65.   8.   4.  10.   9.4  6.9  9. ]
 [ 7.   8.   2.   9.   5.3 10.  10. ]
 [56.   9.   8.   8.   7.4  9.   5. ]
 [ 3.  10.   9.   7.   6.8  5.   6. ]
 [67.   7.   8.   6.   5.   6.   7.7]
 [87.  10.   8.   5.   9.   7.   7. ]
 [ 5.   7.   8.   4.   7.   8.   6. ]]

Transposed Matrix:
[[23.  45.  65.   7.  56.   3.  67.  87.   5. ]
 [ 6.   7.   8.   8.   9.  10.   7.  10.   7. ]
 [ 6.   8.   4.   2.   8.   9.   8.   8.   8. ]
 [ 8.4  6.5 10.   9.   8.   7.   6.   5.   4. ]
 [ 5.   6.4  9.4  5.3  7.4  6.8  5.   9.   7. ]
 [ 7.6  8.6  6.9 10.   9.   5.   6.   7.   8. ]
 [ 7.   8.   9.  10.   5.   6.   7.7  7.   6. ]]

Row Sums:
[ 63.   89.5 112.3  51.3 102.4  46.8 106.7 133.   45. ]

Column Averages:
[39.77777778  8.          6.77777778  7.1         6.81111111  7.56666667
  7.3       ]

Scaled Matrix:
[[ 46.   12.   12.   16.8  10.   15.2  14. ]
 [ 90.   14.   16.   13.   12.8  17.2  16. ]
 [130.   16. 